CREATE TABLE IF NOT EXISTS calculations (
  id SERIAL PRIMARY KEY,
  mrr NUMERIC(10, 2) NOT NULL,
  arr NUMERIC(10, 2) NOT NULL,
  customers INTEGER NOT NULL,
  arpu NUMERIC(10, 2) NOT NULL,
  created_at TIMESTAMP DEFAULT NOW() NOT NULL
);
